### ISSUE TITLE
Make backends as compilation features

### ISSUE THREAD

**Issue by nyurik** [stadiamaps/pmtiles-rs#1]
Each backend should be a separate compilation feature to speed up the build time and reduce external dependencies.

**Comment by lseelenbinder** [comment]
Absolutely!

**Comment by lseelenbinder** [comment]
This is partially addressed in d134a208e5d2f9bd9480c338d29184af7be504ce. More needed, though.

**Comment by lseelenbinder** [comment]
This is done! :fireworks:
