### ISSUE TITLE
Add support for S3 (or compatible) backend

### ISSUE THREAD

**Issue by lseelenbinder** [stadiamaps/pmtiles-rs#11]

**Comment by nyurik** [comment]
Technically this is already implemented -- authentication can be done as URL query params - https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

**Comment by lseelenbinder** [comment]
Wouldn't it still need to calculate the authentication params, since they're partially time-dependent?

**Comment by nyurik** [comment]
good question... seems like it won't work long term.... May want to rename the ticket to protected/private S3, not public
